version: '3.6'
services:
  postgres:
    image: postgres:12
    volumes:
    - ./docker-volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DATABASE: test

  redis:
    image: redis:alpine
    volumes:
      - ./docker-volumes/redis:/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
    - 5050:80
    volumes:
      - "./docker-volumes/pgadmin:/var/lib/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
    depends_on:
    - postgres

  api:
    build: ./api
    environment:
      PORT: 80
      DATABASE_URL: postgres://test:test@postgres:5432/test
      REDISCLOUD_SESSION_URL: redis://redis:6379
    ports:
      - 4000:80
    volumes:
      - "./api/:/app"
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    command: yarn dev

  ui:
    build: ./ui
    environment:
      PORT: 80
      CLIENT_GRAPHQL_URL: "http://localhost:4000/v1/graphql"
      SERVER_GRAPHQL_URL: "http://localhost:4000/v1/graphql"
    ports:
      - 3000:80
      - 6006:6006
    volumes:
      - ./ui:/app
      - /app/node_modules
    command: yarn dev
